[theme]
primaryColor="#c5003c"        # Main accent color (buttons, sliders)
backgroundColor="#00060e"      # Background color
secondaryBackgroundColor="#24030356"  # Sidebar and widget backgrounds
textColor="#FFEF00"           # Text color
