[theme]
primaryColor="#ed0c0cff"        # Main accent color (buttons, sliders)
backgroundColor="#0b0c10"      # Background color
secondaryBackgroundColor="#24030356"  # Sidebar and widget backgrounds
textColor="#FFEF00"           # Text color
